In [1]:
import numpy as np

We can think of broadcasting as a linear algebra version of Python's upcasting feature

In [2]:
A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]
])

In [3]:
print(A)
print("---------------------------")

# Vertical sum
cal = A.sum(axis=0)
print(cal)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
---------------------------
[ 59.  239.  155.4  76.9]


In [4]:
percentage = A / cal
print(percentage)

[[0.94915254 0.         0.02831403 0.88426528]
 [0.02033898 0.43514644 0.33462033 0.10403121]
 [0.03050847 0.56485356 0.63706564 0.01170351]]


#### Generation Broadcasting Principle
- If we have an $(m, n)$ matrix and perform an operation on it with a $(1, n)$ matrix Python will broadcast the $(1, n)$ to be $(m, n)$ then perform the operation.


- If we have an $(m, n)$ matrix and perform an operation on it with a $(m, 1)$ matrix Python will broadcast the $(m, 1)$ to be $(m, n)$ then perform the operation.