### Discrepancies in Numpy
Numpy arrays are supposed to be representations of vectors and matrices. However, they can behave in ways that are un-intuitive to linear algebra students. Here are a few important notes to remember.

In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)
print(a)

[-0.37719234 -0.24767503 -0.31104359  1.85906984 -1.13243388]


In [3]:
print(a.shape)

(5,)


We see that the shape of this array is $(5,)$. This is called a ___Rank 1 Array___ and is neither a row vector or a column vector.

In [4]:
print(a, "shape:", a.shape)
print(a.T, "shape:", a.T.shape)

[-0.37719234 -0.24767503 -0.31104359  1.85906984 -1.13243388] shape: (5,)
[-0.37719234 -0.24767503 -0.31104359  1.85906984 -1.13243388] shape: (5,)


As we can see that a rank 1 array has no transpose, or its transpose is the same shape as its regular shape $(5,)$.

We might think that the dot product of `a` and `a.T` is a 5x5 matrix. But Numpy returns a number:

In [5]:
print(np.dot(a, a.T))

5.038912251082007


__Therefore we should explicitly shape (or reshape) our arrays:__

In [6]:
a = np.random.randn(5, 1)

print(a)

[[ 0.21928376]
 [ 1.03788595]
 [ 2.27532313]
 [ 1.80867954]
 [-0.72628558]]


Now `a` is a column vector.

In [7]:
print(a.T)

[[ 0.21928376  1.03788595  2.27532313  1.80867954 -0.72628558]]


So its transpose is a row vector.

In [8]:
print(np.dot(a, a.T))

[[ 0.04808537  0.22759154  0.49894142  0.39661406 -0.15926264]
 [ 0.22759154  1.07720724  2.36152591  1.87720308 -0.7538016 ]
 [ 0.49894142  2.36152591  5.17709537  4.1153304  -1.65253439]
 [ 0.39661406  1.87720308  4.1153304   3.27132168 -1.31361787]
 [-0.15926264 -0.7538016  -1.65253439 -1.31361787  0.52749075]]


Now, the dot product of `a` and `a.T` is their outter product, a $(5, 5)$ matrix.